import resume from '../../assets/Resume- Timothy Tu.pdf';

function Footer() {
  return (
    <footer className="site-footer" id="footer">
      <div className="footer-intro">
        <p className="eyebrow">Let’s connect</p>
        <h2>More to come<br /><em>soon.</em></h2>
        <p className="footer-message">Have a question, idea, or project in mind? I’d love to hear from you.</p>
      </div>
      <div className="footer-details">
        <a className="button button-light" href="mailto:timothytu0807@gmail.com">Say hello <span aria-hidden="true">↗</span></a>
        <div className="contact-list" aria-label="Contact information">
          <a href="mailto:timothytu0807@gmail.com"><span>Email</span>timothytu0807@gmail.com</a>
          <a href="tel:+1480621351"><span>Phone</span>+1 480 621 2531</a>
          <a href="https://github.com/timothyhzt" target="_blank" rel="noreferrer"><span className="social-icon social-icon--github" aria-hidden="true">GH</span><span className="contact-label"><span>GitHub</span>/timothyhzt <span aria-hidden="true">↗</span></span></a>
          <a href="https://www.linkedin.com/in/timothy-hz-tu" target="_blank" rel="noreferrer"><span className="social-icon social-icon--linkedin" aria-hidden="true">in</span><span className="contact-label"><span>LinkedIn</span>/timothy-tu <span aria-hidden="true">↗</span></span></a>
          <a href="https://www.instagram.com/timothyhztu/?hl=en" target="_blank" rel="noreferrer"><span className="social-icon social-icon--instagram" aria-hidden="true">◎</span><span className="contact-label"><span>Instagram</span>@timothyhzt <span aria-hidden="true">↗</span></span></a>
          <a href={resume} target="_blank" rel="noreferrer"><span className="social-icon social-icon--resume" aria-hidden="true">CV</span><span className="contact-label"><span>Resume</span>View my resume <span aria-hidden="true">↗</span></span></a>
        </div>
        <p className="footer-legal">© 2026 Timothy Tu<br />Made while learning on the web, Images generated by chatgpt</p>
      </div>
    </footer>
  );
}

export default Footer;
